//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSS_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeLov
    {
        public int Id { get; set; }
        public int AttibuteId { get; set; }
        public string Value { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
