//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSS_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Soldout { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<bool> HasAssigned { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}
