//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSS_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSaleDispute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockSaleDispute()
        {
            this.StockShipments = new HashSet<StockShipment>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int StockSaleId { get; set; }
        public int ProductId { get; set; }
        public decimal QuantityClaimed { get; set; }
        public decimal QuantitySent { get; set; }
        public decimal CourierCharges { get; set; }
        public decimal PaypalCharges { get; set; }
        public decimal ProviderCharges { get; set; }
        public decimal ProfitAfterAllCharges { get; set; }
        public string ProviderId { get; set; }
        public int ManagerId { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
        public int Cr_By { get; set; }
        public System.DateTime Cr_At { get; set; }
        public Nullable<int> Up_By { get; set; }
        public Nullable<System.DateTime> Up_At { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StockSale StockSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockShipment> StockShipments { get; set; }
    }
}
